/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingsys;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sam
 */
public class Purchase extends javax.swing.JFrame {

Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
int sl=0;
    public Purchase() {
        initComponents();
        fill();
        jTable1();
    }
     public void cal(){
        float subtotal = Float.valueOf(jTextField4.getText()) * Float.valueOf(jTextField5.getText()) ;
        jTextField6.setText(String.valueOf(subtotal));
        
    }
      public String gettotal(){
        float sum = 0;
        for(int i=0;i<jTable1.getRowCount();i++){
            sum=sum+Float.valueOf((String)jTable1.getValueAt(i, 5));
        }
        return String.valueOf(sum);
    }
public void fill(){
    String date=Datetime.date();
    String time=Datetime.time();
    jTextField8.setText(date);
    jTextField9.setText(time);
    conn=DBConnect.ConnectDB();
String Sql="Select * from Purchase";int c=0;
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
            while(rs.next()){
                 
                c=Integer.valueOf(rs.getString(7));
                        
            
            }
             conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        c++;
       jTextField7.setText(String.valueOf(c));
}


public void jTable1(){
         conn=DBConnect.ConnectDB();
        DefaultTableModel model=null;
        model =(DefaultTableModel)jTable1.getModel();
        String itm=jTextField1.getText();
        String mod=jTextField2.getText();
        String Sql="Select * from ItemInfo where Item  like '%"+itm+"%' and Model like '%"+mod+"%' ";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
              model.setRowCount(0);
             while(rs.next()){    
                        model.addRow(new Object[]{rs.getString(1),rs.getString(2) ,rs.getString(3),rs.getString(4) });
                    
             }
              conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Purchase Bill", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 18), new java.awt.Color(0, 0, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel2.setText("Item :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel7.setText("Model No :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel8.setText("Company Name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel9.setText("Purchase Price:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel10.setText("Quantity :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel11.setText("Net Amount :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 123, 30));

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 123, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 123, 30));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 123, 30));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 123, 30));

        jLabel12.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel12.setText("SL No.:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel13.setText("Date  :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 98, 30));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 98, 30));

        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, 40));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 90, 30));

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 80, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Model", "Company", "Purchase Price", "Quantity", "Rate"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 600, 200));

        jLabel14.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel14.setText("Amount :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 140, 30));

        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 70, 30));

        jLabel15.setFont(new java.awt.Font("Liberation Mono", 1, 14)); // NOI18N
        jLabel15.setText("Bill No. :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 30, 30));

        jButton4.setText("Done");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 90, 40));

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, 90, 40));

        jButton8.setText("Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 150, 70, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ITEM", "MODEL", "M.R.P", "COMPANY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cal();
        conn=DBConnect.ConnectDB();sl++;
//float subtotal = Float.valueOf(jTextField4.getText()) * Float.valueOf(jTextField5.getText()) ;
    //    jTextField6.setText(String.valueOf(subtotal));
        jTextField11.setText(String.valueOf(sl));


DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                       model.addRow(new Object[]{jTextField11.getText(),jTextField1.getText(),jTextField2.getText(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()});


             jTextField10.setText(gettotal());
         
          
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
      
        
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
       
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String time=Datetime.time();
        float subtotal = Float.valueOf(jTextField4.getText()) * Float.valueOf(jTextField5.getText()) ;
        jTextField6.setText(String.valueOf(subtotal));
        if(jTable1.getSelectedRow()==1){
            if(jTable1.getRowCount()<0){
                JOptionPane.showMessageDialog(null,"Selct a Row First ");
            }
        }
        else{
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setValueAt(jTextField1.getText(), jTable1.getSelectedRow(), 0);
        model.setValueAt(jTextField2.getText(), jTable1.getSelectedRow(), 1);
        model.setValueAt(jTextField3.getText(), jTable1.getSelectedRow(), 2);
        model.setValueAt(jTextField4.getText(), jTable1.getSelectedRow(), 3);
        model.setValueAt(jTextField5.getText(), jTable1.getSelectedRow(), 4);
        model.setValueAt(jTextField6.getText(), jTable1.getSelectedRow(), 5);
        jTextField10.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(),5));
     
        jTextField10.setText(gettotal());
        
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int in= JOptionPane.showConfirmDialog(null, "Are you sure ?");
        if(in==0){
        float sum = 0;
        for(int i=0;i<jTable1.getRowCount();i++){
            sum=sum+Float.valueOf((String)jTable1.getValueAt(i, 5));
        }
        jTextField10.setText(String.valueOf(sum));
        //purchase
        for(int i=0;i<jTable1.getRowCount();i++){
                            String date=Datetime.date();
                String time=Datetime.time();
                conn=DBConnect.ConnectDB();
                 String Sql=" insert into Purchase (Item,Model,Company,Rate,Quantity,Date,BillNo,Time,SL)" +" values (?,?, ?,?,?,?,?,?,?) ";
                   try{


                    pst=conn.prepareStatement(Sql);
                    pst.setString(1,(String)jTable1.getValueAt(i, 1));
                    pst.setString(2,(String)jTable1.getValueAt(i, 2));
                    pst.setString(3,jTextField3.getText());
                    pst.setString(4,(String)jTable1.getValueAt(i, 3));
                    pst.setString(5,(String)jTable1.getValueAt(i, 4));
                    pst.setString(6,jTextField8.getText());
                    pst.setString(7,jTextField7.getText());
                    pst.setString(8,time);
                    pst.setString(9,(String)jTable1.getValueAt(i, 0));


                    pst.execute(Sql);
                       
                    conn.close();    
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
                   conn=DBConnect.ConnectDB();
                Sql=" insert into Excange (Date,Time,Item,Model,Rate,Qty,Total,Type,Company,Bill)" +" values (?,?,?,?,?,?,?,?,?, ? ) ";
                  try{


                   pst=conn.prepareStatement(Sql);
                   pst.setString(1,jTextField8.getText());
                   pst.setString(2,jTextField9.getText());
                   pst.setString(3,(String)jTable1.getValueAt(i, 1));
                   pst.setString(4,(String)jTable1.getValueAt(i, 2));
                   pst.setString(5,(String)jTable1.getValueAt(i, 3));
                   pst.setString(6,(String)jTable1.getValueAt(i, 4));
                   pst.setString(7,(String)jTable1.getValueAt(i, 5));
                   pst.setString(8,"Purchased");
                   pst.setString(9,jTextField3.getText());
                   pst.setString(10,jTextField7.getText());
                   pst.execute();
                     conn.close(); 
               }
               catch(Exception e){
                   JOptionPane.showMessageDialog(null,e);
               }   
       }
        JOptionPane.showMessageDialog(null, "Purchase Order Registered ");
        JOptionPane.showMessageDialog(null, "Transaction Added Successfully");

        
        //stockconn=DBConnect.ConnectDB();
       
        for(int i=0;i<jTable1.getRowCount();i++){
                    String qty="";int c=0;
                    conn=DBConnect.ConnectDB();
                           String  Sql="Select * from ItemStock where  Item=? and Model=? ";
                  try{
                      pst=conn.prepareStatement(Sql);
                      pst=conn.prepareStatement(Sql);
                      pst.setString(1,(String)jTable1.getValueAt(i, 1));
                      pst.setString(2,(String)jTable1.getValueAt(i, 2));
                      rs=pst.executeQuery();
                      while(rs.next()){

                          qty = rs.getString("Quantity");c++;

                      }
                       conn.close();
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null,e);
                  }
                    if(c>0){ 
                          float f = Float.valueOf(qty);
                          f=f+Float.valueOf((String)jTable1.getValueAt(i, 4));


conn=DBConnect.ConnectDB();
                          Sql="update ItemStock set Quantity=? where Item=? and Model=? ";
                          try{
                              pst=conn.prepareStatement(Sql);
                              pst.setString(1,String.valueOf(f));
                              pst.setString(2,(String)jTable1.getValueAt(i, 1));
                              pst.setString(3,(String)jTable1.getValueAt(i, 2));
                              pst.executeUpdate();
                            
 conn.close();
                          }
                          catch(Exception e){
                              JOptionPane.showMessageDialog(null,e);
                          }
                          
                    }
                    else{  
                                JOptionPane.showMessageDialog(null, "Item Doesn't Exists");
                    }
                    
                  
        }
        
        JOptionPane.showMessageDialog(null,"Stock Updated Successfully");
        
        
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         
        jTextField1.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        jTextField2.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 1));
       jTextField3.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 2));
    //    jTextField4.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 6));
       // jTextField5.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 5));
        jTextField6.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 5));
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ItemDetails x=new ItemDetails();
          x.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
jTable1();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
jTable1();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        //jTextField1.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        //jTextField2.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        //jTextField3.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 4));
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        //jTextField10.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(),5));
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
